#!/bin/bash
# scripts/generate_module.sh
# Generate a new Python module using Junie agent

# Check arguments
if [ $# -eq 0 ]; then
    echo "Usage: $0 <module_name> [description]"
    echo "Example: $0 my_new_module 'A module for handling data processing'"
    exit 1
fi

MODULE_NAME=$1
DESCRIPTION=${2:-"A new module generated by Junie"}

# Project root
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

# Generate code prompt
PROMPT='Create a Python module named '${MODULE_NAME}'.py in the src/ directory.
Description: '${DESCRIPTION}'
Include proper imports, class definitions, and docstrings.
Follow the existing code style and patterns in the Eugenia project.
The module should integrate well with the existing codebase.'

# Run Junie to generate code
echo "Generating module ${MODULE_NAME}.py..."
./scripts/junie_local.sh "$PROMPT" > /tmp/generated_code.py

# Check if generation was successful
if [ $? -ne 0 ]; then
    echo "Error: Failed to generate code with Junie"
    exit 1
fi

# Extract Python code from output (assuming Junie outputs code after some text)
# This is a simple extraction - may need adjustment based on Junie output format
python_code=$(grep -A 1000 '```python' /tmp/generated_code.py | sed '1d' | sed '/```/q' | sed '$d')

if [ -z "$python_code" ]; then
    echo "Warning: Could not extract Python code from Junie output"
    echo "Raw output saved to /tmp/generated_code.py"
    cat /tmp/generated_code.py
    exit 1
fi

# Write to file
echo "$python_code" > "src/${MODULE_NAME}.py"

echo "Module src/${MODULE_NAME}.py created successfully!"
echo "Please review and test the generated code."